import React, { useState, useMemo } from "react";
import {
  Search,
  MapPin,
  Briefcase,
  Building2,
  Users,
  FileText,
  Sparkles,
  X,
  ChevronDown,
  ExternalLink,
  Mail,
  Linkedin,
  CheckCircle2,
  AlertCircle,
  Loader2,
  Filter,
  ArrowUpRight,
} from "lucide-react";

// ── Mock data (replace with JSearch / Adzuna / Jooble API calls) ─────────────
const MOCK_JOBS = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "Razorpay",
    logo: "RP",
    location: "Bengaluru",
    workMode: "Hybrid",
    experience: "4-7 yrs",
    salary: "₹35-55 LPA",
    posted: "2d ago",
    source: "LinkedIn",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "Tailwind"],
    description:
      "Build payment infrastructure used by 10M+ businesses. Own end-to-end frontend for the merchant dashboard. Strong React + TS, performance optimisation, and design-system thinking required.",
    employees: 2400,
  },
  {
    id: 2,
    title: "Product Designer (Senior)",
    company: "Notion",
    logo: "N",
    location: "Remote (India)",
    workMode: "Remote",
    experience: "5+ yrs",
    salary: "$120-160k",
    posted: "5d ago",
    source: "Indeed",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    description:
      "Shape the next generation of collaborative tools. We're looking for a designer with deep craft, strong systems thinking, and a portfolio that shows opinionated work.",
    employees: 800,
  },
  {
    id: 3,
    title: "Backend Engineer — Distributed Systems",
    company: "Zerodha",
    logo: "Z",
    location: "Bengaluru",
    workMode: "On-site",
    experience: "3-6 yrs",
    salary: "₹28-45 LPA",
    posted: "1d ago",
    source: "Naukri",
    skills: ["Go", "PostgreSQL", "Redis", "Kafka", "System Design"],
    description:
      "Work on the trading systems that power India's largest broker. We process billions of events per day. Looking for engineers who write boring, reliable code.",
    employees: 1100,
  },
  {
    id: 4,
    title: "Engineering Manager, Platform",
    company: "Postman",
    logo: "P",
    location: "Bengaluru",
    workMode: "Hybrid",
    experience: "8+ yrs",
    salary: "₹60-90 LPA",
    posted: "3d ago",
    source: "LinkedIn",
    skills: ["Leadership", "Microservices", "Kubernetes", "AWS", "Mentoring"],
    description:
      "Lead a team of 8-10 engineers building developer-facing API tooling used by 30M+ developers worldwide. Strong technical depth + people-first leadership.",
    employees: 700,
  },
  {
    id: 5,
    title: "Full-Stack Engineer",
    company: "Linear",
    logo: "L",
    location: "Remote",
    workMode: "Remote",
    experience: "3