"""watchlist ats provider+slug

Revision ID: 2f5dcc837dcb
Revises: e2fab17fa5c2
Create Date: 2026-05-02 22:50:22.388338

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5dcc837dcb'
down_revision: str | None = 'e2fab17fa5c2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_company', sa.Column('ats_provider', sa.String(length=32), nullable=True))
    op.add_column('watchlist_company', sa.Column('ats_slug', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_company', 'ats_slug')
    op.drop_column('watchlist_company', 'ats_provider')
    # ### end Alembic commands ###
