"""contact

Revision ID: 33ddd360c069
Revises: f51893f5fe9e
Create Date: 2026-05-02 19:20:15.259311

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ddd360c069'
down_revision: str | None = 'f51893f5fe9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_canonical', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_source', sa.String(length=64), nullable=True),
    sa.Column('signal_json', sa.JSON(), nullable=True),
    sa.Column('briefing_md', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_canonical', 'linkedin_url', name='uq_contact_company_linkedin')
    )
    op.create_index(op.f('ix_contact_company_canonical'), 'contact', ['company_canonical'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_company_canonical'), table_name='contact')
    op.drop_table('contact')
    # ### end Alembic commands ###
