"""job embedding_vector

Revision ID: 422d3c31fba4
Revises: a7d36bf4bdf0
Create Date: 2026-04-26 18:30:50.356512

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422d3c31fba4'
down_revision: str | None = 'a7d36bf4bdf0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('embedding_vector', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'embedding_vector')
    # ### end Alembic commands ###
