"""fit_assessment table

Revision ID: 67e609a26687
Revises: 422d3c31fba4
Create Date: 2026-04-26 18:33:52.721081

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e609a26687'
down_revision: str | None = '422d3c31fba4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fit_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skills_match_json', sa.JSON(), nullable=True),
    sa.Column('experience_verdict', sa.String(length=255), nullable=True),
    sa.Column('domain_match', sa.String(length=255), nullable=True),
    sa.Column('evidence_strength', sa.String(length=255), nullable=True),
    sa.Column('knockout_risks_json', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('summary_md', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_fit_assessment_job')
    )
    op.create_index(op.f('ix_fit_assessment_job_id'), 'fit_assessment', ['job_id'], unique=False)
    op.create_index(op.f('ix_fit_assessment_verdict'), 'fit_assessment', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fit_assessment_verdict'), table_name='fit_assessment')
    op.drop_index(op.f('ix_fit_assessment_job_id'), table_name='fit_assessment')
    op.drop_table('fit_assessment')
    # ### end Alembic commands ###
