"""outreach_draft

Revision ID: 7862d68841c8
Revises: 33ddd360c069
Create Date: 2026-05-02 19:26:05.356856

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7862d68841c8'
down_revision: str | None = '33ddd360c069'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_draft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=True),
    sa.Column('user_edits_json', sa.JSON(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=True),
    sa.Column('reasoning_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_manually_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_draft_contact_id'), 'outreach_draft', ['contact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_draft_contact_id'), table_name='outreach_draft')
    op.drop_table('outreach_draft')
    # ### end Alembic commands ###
