"""trust_assessment + job_repost_history

Revision ID: a774fe90da9e
Revises: 67e609a26687
Create Date: 2026-05-02 18:31:27.000416

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a774fe90da9e'
down_revision: str | None = '67e609a26687'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_repost_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_canonical_id', sa.String(length=64), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('description_hash', sa.String(length=64), nullable=True),
    sa.Column('company_canonical', sa.String(length=255), nullable=True),
    sa.Column('title_normalized', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_repost_history_company_canonical'), 'job_repost_history', ['company_canonical'], unique=False)
    op.create_index(op.f('ix_job_repost_history_job_canonical_id'), 'job_repost_history', ['job_canonical_id'], unique=False)
    op.create_index(op.f('ix_job_repost_history_seen_at'), 'job_repost_history', ['seen_at'], unique=False)
    op.create_table('trust_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('scam_signals_json', sa.JSON(), nullable=True),
    sa.Column('ghost_job_signals_json', sa.JSON(), nullable=True),
    sa.Column('positive_signals_json', sa.JSON(), nullable=True),
    sa.Column('rationale_md', sa.Text(), nullable=True),
    sa.Column('static_check_score', sa.Integer(), nullable=True),
    sa.Column('ai_check_score', sa.Integer(), nullable=True),
    sa.Column('longitudinal_score', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_trust_assessment_job')
    )
    op.create_index(op.f('ix_trust_assessment_job_id'), 'trust_assessment', ['job_id'], unique=False)
    op.create_index(op.f('ix_trust_assessment_verdict'), 'trust_assessment', ['verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_assessment_verdict'), table_name='trust_assessment')
    op.drop_index(op.f('ix_trust_assessment_job_id'), table_name='trust_assessment')
    op.drop_table('trust_assessment')
    op.drop_index(op.f('ix_job_repost_history_seen_at'), table_name='job_repost_history')
    op.drop_index(op.f('ix_job_repost_history_job_canonical_id'), table_name='job_repost_history')
    op.drop_index(op.f('ix_job_repost_history_company_canonical'), table_name='job_repost_history')
    op.drop_table('job_repost_history')
    # ### end Alembic commands ###
