"""job, job_source, search_query

Revision ID: a7d36bf4bdf0
Revises: 7e13ef2dd222
Create Date: 2026-04-26 18:17:35.478612

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d36bf4bdf0'
down_revision: str | None = '7e13ef2dd222'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_canonical', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_mode', sa.String(length=32), nullable=True),
    sa.Column('salary_text', sa.String(length=255), nullable=True),
    sa.Column('description_md', sa.Text(), nullable=True),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apply_url', sa.String(length=1024), nullable=True),
    sa.Column('ats_family', sa.String(length=32), nullable=True),
    sa.Column('embedding_id', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_company'), 'job', ['company'], unique=False)
    op.create_index(op.f('ix_job_company_canonical'), 'job', ['company_canonical'], unique=False)
    op.create_index(op.f('ix_job_first_seen_at'), 'job', ['first_seen_at'], unique=False)
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('locations_json', sa.JSON(), nullable=True),
    sa.Column('work_mode', sa.String(length=32), nullable=True),
    sa.Column('salary_floor', sa.Integer(), nullable=True),
    sa.Column('modes_enabled_json', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_search_query_name')
    )
    op.create_table('job_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_provider', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_source_job_id'), 'job_source', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_source_job_id'), table_name='job_source')
    op.drop_table('job_source')
    op.drop_table('search_query')
    op.drop_index(op.f('ix_job_first_seen_at'), table_name='job')
    op.drop_index(op.f('ix_job_company_canonical'), table_name='job')
    op.drop_index(op.f('ix_job_company'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
