"""tailoring_brief + tailored_artifact

Revision ID: f51893f5fe9e
Revises: a774fe90da9e
Create Date: 2026-05-02 18:46:06.510580

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51893f5fe9e'
down_revision: str | None = 'a774fe90da9e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailoring_brief',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('base_resume_id', sa.Integer(), nullable=False),
    sa.Column('brief_json', sa.JSON(), nullable=False),
    sa.Column('user_edits_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailoring_brief_job_id'), 'tailoring_brief', ['job_id'], unique=False)
    op.create_table('tailored_artifact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('output_file_path', sa.String(length=512), nullable=True),
    sa.Column('truthfulness_passed', sa.Boolean(), nullable=True),
    sa.Column('truthfulness_violations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['tailoring_brief.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_artifact_brief_id'), 'tailored_artifact', ['brief_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_artifact_brief_id'), table_name='tailored_artifact')
    op.drop_table('tailored_artifact')
    op.drop_index(op.f('ix_tailoring_brief_job_id'), table_name='tailoring_brief')
    op.drop_table('tailoring_brief')
    # ### end Alembic commands ###
